### ISSUE TITLE
variance on stocks seems 10x to low?

### ISSUE THREAD

**Issue by wassname** [g-benton/Volt#3]
Thanks for sharing, I had fun playing with this.

Feel free to ignore this if you are busy or have moved on.

I made a fork to try it on random stock data, to see how robust it is. And it seems to work well but the variance is 10x too low, and I'm not sure why.

Example:
- I used the stocks experiment to generate data, and viewed it in [this notebook]( https://github.com/wassname/Volt/blob/main/notebooks/01.00_mjc_view_stock_res.ipynb). You can see the problem in the last graph.
- Also tried modifying it in a notebook (I modified the kernel params etc) and got the same problem. If you search for the word "fixme" you can see where I had to add the x10. https://github.com/wassname/Volt/blob/main/notebooks/00.04_mjc_example_realdata_magpie.ipynb

Curious, I couldn't work it out. Any guesses?

**Comment by g-benton** [comment]
Thanks for checking it out! 

I will look into this a bit more later on, but just scanning through my guess is that there's a subtle mismatch with the `dt` term. If you think about the volatility from an Euler-Maruyama perspective, i.e. just discretely stepping forward in time, you end up with a `\sigma dt` term where `dt` is your step size in time. What this means is that if you learn what `\sigma(t)` is, but `dt` is 10x too small/large then `\sigma(t)` will be 10x too large/small. 

In that notebook we set `dt` to be 1/252 as there's generally 252 trading days in a year so for daily trading that's the step size. If you try to take hourly data or weekly data or alter the spacing of the `x` values you might end up with a situation where the values of `\sigma(t)` are off by some constant factor through some disgreement with the spacing in time. Likely this is also why you noticed that changing the number of steps per unit of time can cause some issues. 

This is a good catch, and probably something I will go back and fix so that it's harder to induce this behavior from the user side once I have a little more time. 

In the meantime, if you're still curious or have a use case you want to try out, it might be worth trying out something more like we do here: https://github.com/g-benton/Volt/blob/47ea8722ffd82c10f85372f9fb14fbf3cf39962b/experiments/stocks/GenerateMultiMeanPreds.py#L100

We're still hard coding `dt` here, but as long as you keep things consistent within that value of `dt` (i.e. see where we set the values of `train_x` and `test_x`) you should be able to avoid those scaling problems.

**Comment by wassname** [comment]
Thanks for the guidance, I'll digest your answer and give it a go :)
